title: XChainjs Documentation
lang: en
description: XChainJS is a library with a common interface for multiple blockchains, built for simple and fast integration for wallets and more. 

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
